name: neodeter_marcaciones
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  http: null
  intl: null
  image_picker: null
  firebase_storage: ^3.1.3
  firebase_messaging: null
  path: null
  barcode_scan: ^3.0.1
  datetime_picker_formfield: ^1.0.0
  flutter_slidable: ^0.5.4
  flutter_secure_storage: ^3.3.1+1
  flutter_full_pdf_viewer: null
  path_provider: null
  provider: ^4.0.4
  camera: null
  firebase_database: null
  firebase_auth: null
  permission_handler: ^3.0.0
  font_awesome_flutter: ^8.8.1
  shared_preferences: ^0.5.7+1
  geolocator: ^6.1.6
  numberpicker: ^0.1.6
  flutter_local_notifications: ^1.4.4+1
  animate_do: null
  calendar_strip: ^1.0.4
  flushbar: ^1.5.0
  uuid: 2.2.0
  device_calendar: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icon/
    - assets/logos/
